student.id=12,43,54,65,75,76

student.address=Sakinaka,Nallasopara,Govandi,Mumbra,Titwala,Kajupada

student.course={'Java':'4 Month','Python':'3 Month','C++':'1 Month','Spring Boot':'2.5 Month','Oops':'15 Days','Collection':'20 Days'}

Student.property={'Hashim Ansari':'Java Developer','Moiez Khan':'Java Developer','Srk Khan':'Mall ke chakkar me'}